### PR TITLE
Add Windows build configuration

### PR DESCRIPTION
**Pull request by wesm**
We need this to build gRPC. See https://issues.apache.org/jira/browse/ARROW-3594

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wesm** [comment]
@conda-forge-admin, please rerender

**Comment by wesm** [comment]
@bagder do you know why the build would be failing with MSVC 9.0 with these errors:

```
[ 14%] Building C object CMakeFiles/c-ares.dir/ares_gethostbyname.c.obj
ares_gethostbyname.c
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(354) : error C2143: syntax error : missing ';' before 'type'
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(355) : error C2275: 'win_platform' : illegal use of this type as an expression
        c:\bld\c-ares_1540653919119\work\ares_platform.h(31) : see declaration of 'win_platform'
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(355) : error C2146: syntax error : missing ';' before identifier 'platform'
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(355) : error C2065: 'platform' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(357) : error C2065: 'PATH_HOSTS' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(357) : error C2109: subscript requires array or pointer type
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(359) : error C2065: 'platform' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(361) : error C2065: 'platform' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(371) : error C2065: 'PATH_HOSTS' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(371) : warning C4047: 'function' : 'LPSTR' differs in levels of indirection from 'int'
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(371) : warning C4024: 'ExpandEnvironmentStringsA' : different types for formal and actual parameter 2
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(375) : error C2065: 'platform' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(376) : error C2065: 'PATH_HOSTS' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(376) : warning C4047: 'function' : 'LPSTR' differs in levels of indirection from 'int'
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(376) : warning C4024: 'GetWindowsDirectoryA' : different types for formal and actual parameter 1
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(380) : error C2065: 'PATH_HOSTS' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(380) : warning C4047: 'function' : 'char *' differs in levels of indirection from 'int'
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(380) : warning C4024: 'strcat' : different types for formal and actual parameter 1
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(390) : error C2065: 'PATH_HOSTS' : undeclared identifier
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(390) : warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'
C:\bld\c-ares_1540653919119\work\ares_gethostbyname.c(390) : warning C4024: 'fopen' : different types for formal and actual parameter 1
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\amd64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error
```

? Thanks!

**Comment by ocefpaf** [comment]
> @ocepaf this should be good once the build passes. PTAL

@wesm let me know if you want to "cash" vc14 by merging this one and sove vc9 in another PR.

**Comment by wesm** [comment]
Sure, can you disable vc < 14 and merge this? I don't need vc9 for what I'm doing right now anyhow

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
